
GET  http://localhost:5025/games

###
GET http://localhost:5025/games/3


###
POST http://localhost:5025/create-games
Content-Type: application/json

{
    "name":"Minecraft",
    "genre":"Kids and Family",
    "price":19.90,
    "releaseDate":"2011-11-18"

}

###
PUT http://localhost:5025/update-games/3
Content-Type: application/json

{
    "name": "Call of Dutys.",
    "genre": "FPS",
    "price": 67.99,
    "releaseDate": "2022-12-20"
  }